#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02).

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "12i add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
