#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo "frontend firstbalance
        bind *:80
        option forwardfor
        default_backend webservers
    backend webservers
        balance roundrobin
        server 3383-web-01 104.196.68.143:80 check
        server 3383-web-02 	54.147.3.4:80 check" > /etc/haproxy/haproxy.cfg
sudo service haproxy restart
