#!/usr/bin/env bash
# This script that gives you information about the [school] file.

Fl="school"
if [ -e "$Fl" ]
then
    echo "$Fl file exists"
    if [ -s "$Fl" ]
    then
        echo "$Fl file is not empty"
    else
        echo "$Fl file is empty"
    fi

    if [ -f "$Fl" ]
    then
        echo "$Fl is a regular file"
    fi

else
    echo "$Fl file does not exist"
fi
